/******************************************************************************
*  Generated by PSoC Designer 5.1.2110.0
******************************************************************************/
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "PSoCGPIOINT.h"
#include "ADC.h"
#include "DAC8_1.h"
#include "USBUART_1.h"

#endif
